// Generated by Ratatosk (`rata codegen`). Do not edit by hand.


import { invoke, channel as rawChannel } from "@elyra/runtime";

/** Any JSON value — `serde_json::Value` on the Rust side. */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type ActionsFilters = {
	status: string,
	branch: string,
	event: string,
	created: string,
	workflow_id: string | null,
};

export type ActionsJob = {
	id: string,
	name: string,
	status: string,
	conclusion: string | null,
	started_at: string | null,
	completed_at: string | null,
	runner: string,
	url: string,
	steps: ActionsStep[],
};

export type ActionsJobs = {
	jobs: ActionsJob[],
	next_page: number | null,
};

export type ActionsLog = {
	text: string,
	truncated: boolean,
};

export type ActionsRun = {
	id: string,
	repository: string,
	workflow_id: string,
	workflow: string,
	title: string,
	number: number,
	attempt: number,
	status: string,
	conclusion: string | null,
	branch: string,
	sha: string,
	event: string,
	actor: string,
	created_at: string,
	updated_at: string,
	started_at: string | null,
	url: string,
};

export type ActionsRuns = {
	runs: ActionsRun[],
	next_page: number | null,
	total: number,
};

export type ActionsStep = {
	number: number,
	name: string,
	status: string,
	conclusion: string | null,
	started_at: string | null,
	completed_at: string | null,
};

export type ActionsWorkflow = {
	id: string,
	repository: string,
	name: string,
	path: string,
	state: string,
	url: string,
};

export type ActionsWorkflows = {
	workflows: ActionsWorkflow[],
	next_page: number | null,
};

export type AgentProbe = {
	ok: boolean,
	error: string | null,
	agent_name: string | null,
	agent_version: string | null,
	protocol_version: number | null,
	load_session: boolean,
	list_sessions?: boolean,
	resume_session?: boolean,
	image: boolean,
	audio: boolean,
	embedded_context: boolean,
	auth_methods: string[],
	options: ConfigOption[],
	commands: SlashCommand[],
	duration_ms: number,
	probed_at: number,
};

export type AgentStatus = {
	id: string,
	name: string,
	transport: Transport,
	experimental: boolean,
	/**  The full ACP launch command, for display. */
	launch: string,
	installed: boolean,
	cli_path: string | null,
	version: string | null,
	auth: Auth,
	auth_detail: string | null,
	/**  For adapters: whether `npx` is available to run them. */
	runner_ok: boolean,
	probe: AgentProbe | null,
	extra_args: string,
};

/**  Release metadata shared by the settings page and native About dialog. */
export type AppInfo = {
	version: string,
	description: string,
	author: string,
	repository: string,
	license: string,
};

export type Attention = {
	kind: AttentionKind,
	detail: string,
	at: number,
};

export type AttentionKind = "permission" | "failed" | "review";

export type Auth = "ok" | "logged_out" | "unknown";

/**
 *  A change to push to the frontend. `version` counts changes per entry:
 *  an `Upsert` is a full snapshot (apply if newer); an `AppendText` must be
 *  exactly `local + 1`, otherwise the frontend resyncs.
 */
export type Change = { op: "upsert"; index: number; version: number; entry: Entry } | { op: "append_text"; index: number; version: number; delta: string };

export type Choice = {
	value: string,
	name: string,
	description: string | null,
};

export type CommandFile = {
	agent: string,
	/**  As typed after `/`: subfolders become namespaces (`git:commit`). */
	name: string,
	path: string,
	project: string | null,
};

/**  A select-type session config option (model, mode, effort…). */
export type ConfigOption = {
	id: string,
	name: string,
	category: string,
	current: string,
	choices: Choice[],
};

/**  Direction of a raw line, from Splash's point of view. */
export type Dir = "out" | "in";

export type DirEntry = {
	name: string,
	path: string,
	is_dir: boolean,
};

export type Doc = {
	path: string,
	frontmatter: DocField[],
	body: string,
};

export type DocField = {
	key: string,
	value: JsonValue,
};

export type Entry = { kind: "user"; text: string } | { kind: "agent"; text: string; streaming: boolean } | { kind: "thought"; text: string; streaming: boolean } | { kind: "tool"; id: string; title: string; 
/**  ACP tool kind: read, edit, delete, move, search, execute, think, fetch, other. */
tool_kind: string; 
/**  pending, in_progress, completed, failed. */
status: string; locations: Location[]; content: ToolContent[]; 
/**  A one-line summary of the raw input (command, path, query…). */
input: string | null; 
/**  Raw output as text, truncated. */
output: string | null } | { kind: "plan"; items: PlanItem[] } | { kind: "permission"; request_id: string; title: string; tool_id: string | null; options: PermissionChoice[]; 
/**  The chosen option id, `"cancelled"`, or `None` while waiting. */
resolution: string | null } | { kind: "divider"; text: string } | { kind: "error"; text: string } | 
/**  Agent output outside any turn (startup warnings, MCP failures…). */
{ kind: "notice"; text: string } | 
/**  A `session/update` we don't understand, kept verbatim. */
{ kind: "unknown"; json: string } | { kind: "turn_end"; stop_reason: string; duration_ms: number };

export type ExternalSession = {
	session_id: string,
	cwd: string,
	title: string | null,
	updated_at: string | null,
};

export type FileChange = {
	/**  Relative to the session folder. */
	path: string,
	/**  M modified, A added, D deleted, ? untracked, T type change. */
	status: string,
	additions: number,
	deletions: number,
	binary: boolean,
};

export type FileContent = {
	path: string,
	text: string | null,
	binary: boolean,
	too_large: boolean,
	size: number,
};

export type FileDiff = {
	path: string,
	/**  At the base commit; `None` when the file is new. */
	old: string | null,
	/**  On disk; `None` when deleted. */
	new: string | null,
	binary: boolean,
	too_large: boolean,
};

export type GitInfo = {
	/**  `github.com/owner/repo`, for display. */
	repo: string | null,
	/**  `https://github.com/owner/repo`. */
	web_url: string | null,
	branch: string | null,
	/**  The branch on the web, when there is a web URL. */
	branch_url: string | null,
	pr: PullRequest | null,
};

export type GithubCatalog = {
	login: string,
	repositories: GithubRepository[],
};

export type GithubComment = {
	author: string,
	body: string,
	url: string,
	created_at: string,
};

export type GithubComments = {
	comments: GithubComment[],
	has_more: boolean,
};

export type GithubItem = {
	id: string,
	repository: string,
	kind: GithubKind,
	number: number | null,
	title: string,
	body: string,
	url: string,
	state: string,
	updated_at: string,
	author: string,
	assignees: string[],
	reviewers: string[],
	labels: string[],
	branch: string | null,
	checks: string | null,
	review_decision: string | null,
};

export type GithubKind = "issue" | "pull_request" | "branch" | "activity";

export type GithubPage = {
	items: GithubItem[],
	next_cursor: string | null,
};

export type GithubRepository = {
	full_name: string,
	owner: string,
	private: boolean,
	archived: boolean,
	has_issues: boolean,
	updated_at: string,
	project_ids: string[],
};

export type GithubSearch = {
	text: string,
	author: string,
	assignee: string,
	label: string,
	review: string,
	state: string,
};

export type HistoryCapabilities = {
	list: boolean,
	load: boolean,
	resume: boolean,
};

export type HistoryPage = {
	capabilities: HistoryCapabilities,
	sessions: ExternalSession[],
	next_cursor: string | null,
};

export type Isolation = "in_place" | "worktree";

export type Location = {
	path: string,
	line: number | null,
};

export type McpList = {
	servers: McpServer[],
	errors: McpSourceError[],
};

export type McpServer = {
	agent: string,
	name: string,
	/**  stdio, http, sse… */
	transport: string,
	/**  The command line or URL (never headers or env values). */
	target: string,
	enabled: boolean,
	header_keys: string[],
	env_keys: string[],
	/**  The config file it came from. */
	source: string,
	/**  For project-scoped servers (Claude's per-project config). */
	project: string | null,
};

export type McpSourceError = {
	agent: string,
	source: string,
	error: string,
};

export type PermissionChoice = {
	id: string,
	name: string,
	/**  allow_once, allow_always, reject_once, reject_always. */
	kind: string,
};

export type PlanItem = {
	content: string,
	priority: string,
	status: string,
};

export type Project = {
	id: string,
	name: string,
	path: string,
	is_git: boolean,
	created_at: number,
};

export type PullRequest = {
	number: number,
	url: string,
	/**  OPEN, CLOSED, MERGED. */
	state: string,
	title: string,
};

export type RpcLine = {
	session: string,
	dir: Dir,
	/**  Seconds since the epoch. */
	at: number,
	line: string,
};

export type SessionMatch = {
	session_id: string,
	entry_index: number,
	excerpt: string,
};

/**  Everything about a live session that isn't transcript. */
export type SessionMeta = {
	/**  Config options, falling back to legacy `modes` as a synthetic "mode" option. */
	options: ConfigOption[],
	/**  True when `options` holds legacy modes (changed via `session/set_mode`). */
	legacy_modes: boolean,
	commands: SlashCommand[],
	usage: Usage | null,
	title: string | null,
};

export type SessionPreview = {
	token: string,
	agent_id: string,
	session_id: string,
	cwd: string,
	title: string,
	entries: Entry[],
};

export type SessionRecord = {
	id: string,
	project_id: string,
	agent_id: string,
	title: string,
	cwd: string,
	isolation: Isolation,
	branch: string | null,
	base_sha: string | null,
	agent_session_id: string | null,
	archived: boolean,
	created_at: number,
	updated_at: number,
	/**  The last usage the agent reported (context, cost), kept across restarts. */
	usage: Usage | null,
	/**  External conversations never own their directory or provider history. */
	external?: boolean,
	/**  The launch profile used when importing (None follows current settings). */
	launch_args?: string | null,
	attention?: Attention | null,
};

/**  A session as the UI sees it: the stored record plus live state. */
export type SessionView = {
	status: Status,
	detail: string | null,
	meta: SessionMeta,
} & SessionRecord;

export type Skill = {
	name: string,
	description: string,
	/**  The skill's folder. */
	path: string,
	/**  Where it was found, for grouping (`~/.claude/skills`). */
	source: string,
	/**  Agents that read this location (empty for shared `.agents/skills`). */
	agents: string[],
	/**  The project it belongs to, for project-level skills. */
	project: string | null,
	/**  `user-invocable: false` hides it from the `/` menu (Claude). */
	user_invocable: boolean,
	/**  `disable-model-invocation: true`: only runs when called by name. */
	manual_only: boolean,
};

export type SlashCommand = {
	name: string,
	description: string,
	hint: string | null,
};

export type Status = "starting" | "idle" | "running" | "awaiting_permission" | "error" | "exited";

export type TermAttach = {
	/**  Everything still in the scrollback, base64. */
	scrollback: string,
	/**  The last sequence number included in `scrollback`. */
	seq: number,
};

export type TermEvent = {
	session: string,
	seq: number,
	/**  Base64 bytes (specta would type `Vec<u8>` as `number[]`). */
	data: string,
	exited: boolean,
};

export type ToolContent = { type: "text"; text: string } | { type: "diff"; path: string; old: string | null; new: string } | { type: "terminal"; id: string };

/**  Pushed on `transcript`: one flush worth of changes for one session. */
export type TranscriptEvent = {
	session: string,
	changes: Change[],
};

/**  A transcript with per-entry versions, for (re)syncing the frontend. */
export type TranscriptSnapshot = {
	entries: Entry[],
	versions: number[],
};

export type Transport = 
/**  The CLI itself serves ACP (`glue acp`, `pool acp`). */
"native" | 
/**  An npm package bridges ACP to the vendor CLI. */
"adapter";

export type Usage = {
	used: number,
	size: number,
	cost_usd: number | null,
	/**  Numbers the agent adds in `_meta` (input/output/cached tokens…). */
	extra: UsageExtra[],
};

export type UsageExtra = {
	label: string,
	value: number,
};

/**  Pushed on `workspace` when files in a session's folder probably changed. */
export type WorkspaceEvent = {
	session: string,
	paths: string[],
};

export const api = {
  acknowledge_session(id: string): Promise<null> {
    return invoke("acknowledge_session", id);
  },
  add_project(path: string): Promise<Project> {
    return invoke("add_project", path);
  },
  app_info(): Promise<AppInfo> {
    return invoke("app_info");
  },
  archive_session(id: string, force: boolean): Promise<null> {
    return invoke("archive_session", id, force);
  },
  cancel(id: string): Promise<null> {
    return invoke("cancel", id);
  },
  create_session(project_id: string, agent_id: string, isolation: Isolation, title: string | null): Promise<SessionView> {
    return invoke("create_session", project_id, agent_id, isolation, title);
  },
  delete_session(id: string, force: boolean): Promise<null> {
    return invoke("delete_session", id, force);
  },
  discover_sessions(agent_id: string, cwd: string, cursor: string | null): Promise<HistoryPage> {
    return invoke("discover_sessions", agent_id, cwd, cursor);
  },
  file_diff(id: string, path: string): Promise<FileDiff> {
    return invoke("file_diff", id, path);
  },
  get_settings(): Promise<{ [key in string]: string }> {
    return invoke("get_settings");
  },
  github_actions_jobs(repository: string, run_id: string, attempt: number, page: number): Promise<ActionsJobs> {
    return invoke("github_actions_jobs", repository, run_id, attempt, page);
  },
  github_actions_log(repository: string, job_id: string): Promise<ActionsLog> {
    return invoke("github_actions_log", repository, job_id);
  },
  github_actions_runs(repository: string, filters: ActionsFilters, page: number): Promise<ActionsRuns> {
    return invoke("github_actions_runs", repository, filters, page);
  },
  github_actions_workflows(repository: string, page: number): Promise<ActionsWorkflows> {
    return invoke("github_actions_workflows", repository, page);
  },
  github_catalog(): Promise<GithubCatalog> {
    return invoke("github_catalog");
  },
  github_comments(repository: string, number: number, kind: GithubKind): Promise<GithubComments> {
    return invoke("github_comments", repository, number, kind);
  },
  github_create_issue(repository: string, title: string, body: string): Promise<GithubItem> {
    return invoke("github_create_issue", repository, title, body);
  },
  github_link_project(repository: string, project_id: string | null): Promise<null> {
    return invoke("github_link_project", repository, project_id);
  },
  github_page(repository: string, kind: GithubKind, cursor: string | null): Promise<GithubPage> {
    return invoke("github_page", repository, kind, cursor);
  },
  github_search(repositories: string[], kind: GithubKind, filters: GithubSearch, cursor: string | null): Promise<GithubPage> {
    return invoke("github_search", repositories, kind, filters, cursor);
  },
  github_work_session(project_id: string, agent_id: string, repository: string, number: number, title: string): Promise<SessionView> {
    return invoke("github_work_session", project_id, agent_id, repository, number, title);
  },
  import_session(token: string): Promise<SessionView> {
    return invoke("import_session", token);
  },
  list_agents(refresh: boolean): Promise<AgentStatus[]> {
    return invoke("list_agents", refresh);
  },
  list_command_files(): Promise<CommandFile[]> {
    return invoke("list_command_files");
  },
  list_dir(id: string, path: string): Promise<DirEntry[]> {
    return invoke("list_dir", id, path);
  },
  list_mcp_servers(): Promise<McpList> {
    return invoke("list_mcp_servers");
  },
  list_projects(): Promise<Project[]> {
    return invoke("list_projects");
  },
  list_sessions(): Promise<SessionView[]> {
    return invoke("list_sessions");
  },
  list_skills(): Promise<Skill[]> {
    return invoke("list_skills");
  },
  open_session(id: string): Promise<TranscriptSnapshot> {
    return invoke("open_session", id);
  },
  preview_session(agent_id: string, cwd: string, session_id: string): Promise<SessionPreview> {
    return invoke("preview_session", agent_id, cwd, session_id);
  },
  probe_agent(id: string): Promise<AgentStatus> {
    return invoke("probe_agent", id);
  },
  read_doc(path: string): Promise<Doc> {
    return invoke("read_doc", path);
  },
  read_file(id: string, path: string): Promise<FileContent> {
    return invoke("read_file", id, path);
  },
  remove_project(id: string): Promise<null> {
    return invoke("remove_project", id);
  },
  rename_session(id: string, title: string): Promise<null> {
    return invoke("rename_session", id, title);
  },
  resolve_permission(id: string, request_id: string, option_id: string | null): Promise<null> {
    return invoke("resolve_permission", id, request_id, option_id);
  },
  restart_session(id: string): Promise<null> {
    return invoke("restart_session", id);
  },
  rpc_log(id: string): Promise<RpcLine[]> {
    return invoke("rpc_log", id);
  },
  search_sessions(query: string): Promise<SessionMatch[]> {
    return invoke("search_sessions", query);
  },
  send_prompt(id: string, text: string): Promise<null> {
    return invoke("send_prompt", id, text);
  },
  session_git(id: string, refresh: boolean): Promise<GitInfo> {
    return invoke("session_git", id, refresh);
  },
  session_transcript(id: string): Promise<TranscriptSnapshot> {
    return invoke("session_transcript", id);
  },
  set_agent_args(id: string, args: string): Promise<AgentStatus> {
    return invoke("set_agent_args", id, args);
  },
  set_option(id: string, option: string, value: string): Promise<null> {
    return invoke("set_option", id, option, value);
  },
  set_setting(key: string, value: string): Promise<null> {
    return invoke("set_setting", key, value);
  },
  term_close(id: string): Promise<null> {
    return invoke("term_close", id);
  },
  term_open(id: string, cols: number, rows: number): Promise<TermAttach> {
    return invoke("term_open", id, cols, rows);
  },
  term_resize(id: string, cols: number, rows: number): Promise<null> {
    return invoke("term_resize", id, cols, rows);
  },
  term_write(id: string, data: string): Promise<null> {
    return invoke("term_write", id, data);
  },
  watch_rpc(id: string, on: boolean): Promise<null> {
    return invoke("watch_rpc", id, on);
  },
  watch_workspace(id: string, on: boolean): Promise<null> {
    return invoke("watch_workspace", id, on);
  },
  workspace_status(id: string): Promise<FileChange[]> {
    return invoke("workspace_status", id);
  },
};

/** Every event channel the Rust side emits, with its payload. */
export type ElyraEvents = {
  "agents": AgentStatus;
  "project": Project;
  "rpc": RpcLine;
  "session": SessionView;
  "term": TermEvent;
  "transcript": TranscriptEvent;
  "workspace": WorkspaceEvent;
};

/** A channel name known to the Rust side. */
export type ElyraEventName = keyof ElyraEvents;

/**
 * Subscribe to a typed event channel. Unlike the untyped
                     * `channel()` from `@elyra/runtime`, both the name and the payload
                     * are checked against the Rust definitions.
 */
export function channel<K extends ElyraEventName>(
  name: K,
): {
  subscribe: (handler: (value: ElyraEvents[K] | undefined) => void) => () => void;
} {
  return rawChannel<ElyraEvents[K]>(name);
}

