Unicode True
!include "MUI2.nsh"
!include "FileFunc.nsh"
!define UNINSTALL_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\Splash"
Name "Splash"
OutFile "${OUTPUT}"
InstallDir "$LOCALAPPDATA\Programs\Splash"
RequestExecutionLevel user
BrandingText "Splash ${VERSION}"
; Generated by scripts/generate-icons.py; relative to this script.
!define MUI_ICON "icons\splash.ico"
!define MUI_UNICON "icons\splash.ico"
!define MUI_ABORTWARNING
; File properties of the installer itself. VERSION_NUMERIC is MAJOR.MINOR.PATCH.0.
VIProductVersion "${VERSION_NUMERIC}"
VIFileVersion "${VERSION_NUMERIC}"
VIAddVersionKey /LANG=1033 "ProductName" "Splash"
VIAddVersionKey /LANG=1033 "CompanyName" "Helge Sverre"
VIAddVersionKey /LANG=1033 "FileDescription" "Splash installer"
VIAddVersionKey /LANG=1033 "FileVersion" "${VERSION}"
VIAddVersionKey /LANG=1033 "ProductVersion" "${VERSION}"
VIAddVersionKey /LANG=1033 "LegalCopyright" "Copyright © 2026 Helge Sverre. MIT License."
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
Section "Splash"
  SetOutPath "$INSTDIR"
  File "${SOURCE}\splash.exe"
  File "${SOURCE}\LICENSE"
  File "${SOURCE}\README.txt"
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  CreateDirectory "$SMPROGRAMS\Splash"
  CreateShortcut "$SMPROGRAMS\Splash\Splash.lnk" "$INSTDIR\splash.exe"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayName" "Splash"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayIcon" '"$INSTDIR\splash.exe",0'
  WriteRegStr HKCU "${UNINSTALL_KEY}" "Publisher" "Helge Sverre"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "URLInfoAbout" "https://github.com/HelgeSverre/splash"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegStr HKCU "${UNINSTALL_KEY}" "QuietUninstallString" '"$INSTDIR\Uninstall.exe" /S'
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "EstimatedSize" "$0"
SectionEnd
Section "Uninstall"
  Delete "$INSTDIR\splash.exe"
  Delete "$INSTDIR\LICENSE"
  Delete "$INSTDIR\README.txt"
  Delete "$INSTDIR\Uninstall.exe"
  Delete "$SMPROGRAMS\Splash\Splash.lnk"
  RMDir "$SMPROGRAMS\Splash"
  RMDir "$INSTDIR"
  DeleteRegKey HKCU "${UNINSTALL_KEY}"
  ; User conversations/configuration are deliberately retained.
SectionEnd
